# Generated by Django 5.0.4 on 2024-05-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_tags_blogmodel_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='name',
        ),
    ]
